config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  get 'home/index'
  get 'home/about'
  root 'home#index'
  post "/" => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:id] == ""
      @nothing = "You forgot to enter a symbol ;)."
    elsif

      if params[:id]
        begin
        @stock = IEX::Resources::Quote.get(params[:id])
        @company = IEX::Resources::Company.get(params[:id])
        rescue StandardError
        @error = "That stock symbol doesn't seem to exist. Please enter another symbol."
        end



      end

    end

  end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end

    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "Not authorized to edit this stock." if @ticker.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
  <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stocker", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", home_about_path %></li>

        <% if user_signed_in? %>
        <li><%= link_to "List Stocks", stocks_path %></li>
        <li><%= link_to "Add Stock", new_stock_path %></li>
        <li><%= link_to "Update Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log Out",  destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

app/views/home/about.html.erb
<h1>About us</h1>
<p>Description here</p>

app/views/home/index.html.erb
<br/><br/>
<%= form_tag root_path, :method => 'POST' do %>
<%= text_field_tag 'id', nil, placeholder: 'Enter Company Ticker Symbol', size: 50 %>
<%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<br/><br/>

<% if @stock %>

<strong>Company: </strong><%= @company.company_name %><br>
<strong>CEO: </strong><%= @company.ceo %><br>
<strong>Latest Price: </strong><%= @stock.latest_price %><br>
<strong>Percent Change: </strong><%= @stock.change_percent_s %><br>
<strong>Description: </strong><%= @company.description %><br>

<% elsif @nothing %>
  <%= @nothing %>
<% end %>

<% if @error %>
<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stocker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>

    <%= render 'home/navbar' %>

    <div class="container">
    <%= render 'home/flash' %>
      <%= yield %>
    </div>

  </body>

</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.text_field :user_id, value: current_user.id, type: :hidden, class: "form-control" %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Company Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
        <% begin %>
          <% @stock_quote = IEX::Resources::Quote.get(stock.ticker) %>
          <% @company = IEX::Resources::Company.get(stock.ticker) %>
        <% rescue StandardError %>
          <tr>
            <td><%= stock.ticker %></td>
            <td><%= "N/A" %></td>
            <td><%= "N/A" %></td>
            <td><%= link_to 'Show', stock, class: "btn btn-default" %></td>
            <td><%= link_to 'Edit', edit_stock_path(stock), class: "btn btn-default" %></td>
            <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
          </tr>
          <% next %>
        <% end %>
        <tr>
          <td><%= stock.ticker %></td>
          <td><%= @stock_quote.latest_price %></td>
          <td><%= @company.company_name %></td>
          <td><%= link_to 'Show', stock, class: "btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock), class: "btn btn-default" %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Stock', new_stock_path, class: "btn btn-default" %>

<br><br>

<br/><br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Quick Quotes</h3>
  </div>
  <div class="panel-body">
    <%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'id', nil, placeholder: 'Enter Ticker Symbol Here', size: 50 %>
    <%= submit_tag 'Click Here' %>
    <% end %>
  </div>
</div>

app/views/stocks/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Stock</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', stock: @stock %>
  </div>
  <div class="panel-footer"><%= link_to 'Back', stocks_path %></div>
</div>

app/views/stocks/show.html.erb
<% begin %>
  <% @stock_quote = IEX::Resources::Quote.get(@stock.ticker) %>
  <% @company = IEX::Resources::Company.get(@stock.ticker) %>
<% rescue StandardError %>
  hello
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong><%= @company.company_name %> - <%= @stock_quote.symbol %></strong></h3>
  </div>
  <div class="panel-body">
    <h1>$<%= @stock_quote.latest_price %></h1><br>
    <strong>CEO: </strong><%= @company.ceo %><br><br>
    <strong>Percent Change: </strong><%= @stock_quote.change_percent_s %><br><br>
    <strong>Description: </strong><%= @company.description %><br><br>
  </div>
  <div class="panel-footer"><%= link_to 'Edit', edit_stock_path(@stock), class: "btn btn-default" %>
  <%= link_to 'Delete', stock_path(@stock), method: :delete, data:
              { confirm: 'Are you sure?' }, class: "btn btn-default" %>
  <%= link_to 'Back', stocks_path, class: "btn btn-default" %></div></div>
</div>